// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fskubayfvudjrqndlmph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZza3ViYXlmdnVkanJxbmRsbXBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU0ODQ4ODksImV4cCI6MjA1MTA2MDg4OX0.mQbDdnmDhoX3Il4MlbYakwQ7AH32ykbqTuUSRTzCBXA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);